language: objective-c
osx_image: xcode8.1
script:
  - xcodebuild clean test -project ./SwiftProtocolsAndGeneric/SwiftProtocolsAndGeneric.xcodeproj -scheme SwiftProtocolsAndGeneric -destination 'platform=iOS Simulator,name=iPhone 7' TEST_AFTER_BUILD=YES -configuration Debug -enableCodeCoverage=YES
